---
title: Proceedings of Machine Learning Research
booktitle: Proceedings of the 7th Northern Lights Deep Learning Conference (NLDL)
shortname: NLDL
year: '2026'
publisher: PMLR
series: Proceedings of Machine Learning Research
volume: '307'
start: &1 2026-01-06
end: 2026-01-08
published: 2026-01-19
conference_number: '7'
layout: proceedings
issn: 2640-3498
id: nldl2026
month: 0
tex_title: Proceedings of the 7th Northern Lights Deep Learning Conference (NLDL)
cycles: false
bibtex_editor: Kim, Hyeongji and Ram\'irez Rivera, Ad\'in and Ricaud, Benjamin
editor:
- given: Hyeongji
  family: Kim
- given: Adín
  family: Ramírez Rivera
- given: Benjamin
  family: Ricaud
description: |
  Proceedings of the 7th Northern Lights Deep Learning Conference (NLDL)
    Held in UiT The Arctic University, Troms\o, Norway on 06-08 January 2026

  Published as Volume 307 by the Proceedings of Machine Learning Research on 19 January 2026.

  Volume Edited by:
    Hyeongji Kim
    Adín Ramírez Rivera
    Benjamin Ricaud

  Series Editors:
    Neil D. Lawrence
date_str: 06--08 Jan
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v307"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v307
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v307
email: ''
conference:
  name: Northern Lights Deep Learning Conference
  url: https://www.nldl.org
  location: UiT The Arctic University, Tromsø, Norway
  dates:
  - *1
  - 2026-01-07
  - 2026-01-08
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: nldl2026_cleaned_clean.bib
# Site settings
# Original source:  nldl2026_cleaned_clean.bib
